### ISSUE TITLE
Machine Learning

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#78]
**Is your feature request related to a problem? Please describe.**
Allow the calculation to use machine learning for result calculation

**TODO (non-ordered)**
- [ ] allow `submitAnswers()` to use different calculation methods
- [ ] Add suffix to `UserSession` to distinguish regular from machine learning results
- [ ] Implement training model
- [ ] do performance checks 
- [ ] Implement test mode (e. g. random users get machine learning results)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
All of this is obviously improvemental, but the phrasal of the last task is weird, because randomness is impossible for digital computers. Consequently, potentially evaluate what the most rational method of determination of which users of the service should be tested is.
