### ISSUE TITLE
Distribution additions

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#94]
# Distribution proposed to add

- [x] Deepin (reported in https://github.com/distrochooser/distrochooser/issues/91)
- [ ] antiX (reported in https://github.com/distrochooser/distrochooser/issues/91)
- [ ] Sparky Linux (reported in https://github.com/distrochooser/distrochooser/issues/91)
- [x] Pop!_OS (reported via mail)
- [ ] Peppermint OS (reported in https://github.com/distrochooser/distrochooser/issues/94#issuecomment-678560832)

**Comment by 6543** [comment]
for artiX: you can use same values as Arch, just the no-systemd feature checked and you may need a bit more expertice ... thats it

**Comment by pbhj** [comment]
I use Kubuntu, Ubuntu is recommended to me but honestly I dislike it a lot (because I'm used to KDE).

I guess the while thing is targeted to new users, but the question on Win/Mac familiarity could include major DEs, like if I'd tried a distro with KDE and wanted that but needed something tailored in other aspects.

Similarly I don't like snaps and would not want to try a new distro that uses that. I guess the choices are higher level.

**Comment by omeritzics** [comment]
HI, could you add Mageia, please? It is one of the distributions which did not drop out 32bit system support, and it has a wide driver support (if I'm not wrong).

**Comment by yxsos** [comment]
Hi, I am the project manager of deepin.  
I saw the recommendation without Deepin on the website. How can I add the recommendation list

**Comment by cmllr** [comment]
@yxsos I need to know aspects about the Distribution: Especially what it's core concepts are and what the differences compared to Debian are. Can you provide that?

**Comment by yxsos** [comment]
> @yxsos I need to know aspects about the Distribution: Especially what it's core concepts are and what the differences compared to Debian are. Can you provide that?

cmllr,Hi!
1.The core concepts of deepin is DDE(deepin desktop environment),It is a desktop environment developed by us, with light, beautiful, and stable as the design goal.
2.deepin is a derivative community based on the Debian department. It is currently based on the Debian 10 version in terms of the bottom level of the system.

**Comment by cmllr** [comment]
> @yxsos

thank you! I have some additional questions and created a discussion on https://github.com/distrochooser/distrochooser/discussions/170 so we can discuss them there.

**Comment by Lord-Valen** [comment]
It would be great to add NixOS. It's great for multiple devices and devops given that it's a declarative OS. You can also generate ISOs quite easily (via [nixos-generators](https://github.com/nix-community/nixos-generators)), making it especially suitable for live boot. Many think the barrier to entry is quite high but [nix-gui](https://github.com/nix-gui/nix-gui) and the addition of the GUI installer in 22.05 should mitigate this. NixOS should be manageable for an intermediate user.

**Comment by cmllr** [comment]
@Lord-Valen NixOS is already in the list, but I adapted the decision matrix as there where some mappings for it missing.

**Comment by cmllr** [comment]
I will close this issue in favor of distribution specific issue creation.
