### ISSUE TITLE
Question addititions

### ISSUE THREAD

**Issue by cmllr** [distrochooser/distrochooser#97]
* [ ] Add question about touch support, especially convertibles (requested via mail and via #62)
* [ ] Add desktop specific questions (as requested in #56)
* [ ] Graphics card support (as requested in #99)

**Comment by cmllr** [comment]
Closing this issue in favor of proper labels.
